services:
  mongodb:
    image: mongo:8
    container_name: aeroscan-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aeroscan-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/aeroscan
      PORT: 3000
    depends_on:
      - mongodb

volumes:
  mongodb_data: